name: partonomy
channels:
  - pytorch
  - nvidia/label/cuda-11.7.0
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.1.4
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvcc=11.7.64
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.5
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.17.2
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.5.0
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.10.0.4
  - libcurand=10.3.6.39
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=3.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.16
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.3.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.3.0
  - torchtriton=2.3.0
  - tornado=6.1
  - traitlets=5.13.0
  - wcwidth=0.2.10
  - wget=1.21.4
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - accelerate==0.21.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.1.2
      - anyio==3.7.1
      - appdirs==1.4.4
      - asgiref==3.8.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.12.2
      - bert-score==0.3.13
      - bitsandbytes==0.41.0
      - blessed==1.20.0
      - blis==0.7.11
      - bs4==0.0.2
      - build==1.2.2.post1
      - cachetools==5.3.2
      - catalogue==2.0.10
      - certifi==2023.7.22
      - cffi==1.17.1
      - charset-normalizer==3.1.0
      - chroma-hnswlib==0.7.6
      - chromadb==1.0.12
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cmake==3.27.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - confection==0.1.4
      - contourpy==1.2.0
      - cragmm-search-pipeline==0.5.0
      - crcmod==1.7
      - cryptography==44.0.2
      - cycler==0.12.1
      - cymem==2.0.8
      - datasets==2.16.1
      - deepspeed==0.9.5
      - defusedxml==0.7.1
      - dill==0.3.7
      - distro==1.8.0
      - docker-pycreds==0.4.0
      - durationpy==0.10
      - einops==0.6.1
      - einops-exts==0.0.4
      - faiss-gpu-cu11==1.12.0
      - fastapi==0.104.1
      - ffmpy==0.3.1
      - filelock==3.14.0
      - flash-attn==2.6.3
      - flatbuffers==25.2.10
      - fonttools==4.44.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - ftfy==6.3.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.26.1
      - google-auth-oauthlib==1.2.0
      - googleapis-common-protos==1.70.0
      - gpustat==1.1.1
      - gradio==3.35.2
      - gradio-client==0.2.9
      - groundingdino==0.1.0
      - grpcio==1.60.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==0.17.3
      - httptools==0.6.4
      - httpx==0.24.0
      - huggingface-hub==0.20.1
      - humanfriendly==10.0
      - idna==3.4
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - jinja2==3.1.2
      - jmespath==0.10.0
      - joblib==1.3.2
      - jsonargparse==4.37.0
      - jsonlines==2.0.0
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.11.1
      - kiwisolver==1.4.5
      - kubernetes==32.0.1
      - langcodes==3.3.0
      - lazy-loader==0.4
      - lightning-utilities==0.10.0
      - linkify-it-py==2.0.2
      - lit==17.0.5
      - llava==1.1.1
      - lmdb==1.6.2
      - markdown==3.5.1
      - markdown-it-py==2.2.0
      - markdown2==2.4.10
      - matplotlib==3.8.1
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mmh3==5.1.0
      - model-index==0.1.11
      - more-itertools==10.6.0
      - mpi4py==4.1.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - murmurhash==1.0.10
      - ninja==1.11.1.1
      - nltk==3.8.1
      - numpy==1.26.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - onnxruntime==1.22.0
      - openai==1.3.4
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - opentelemetry-api==1.34.0
      - opentelemetry-exporter-otlp-proto-common==1.34.0
      - opentelemetry-exporter-otlp-proto-grpc==1.34.0
      - opentelemetry-instrumentation==0.55b0
      - opentelemetry-instrumentation-asgi==0.55b0
      - opentelemetry-instrumentation-fastapi==0.55b0
      - opentelemetry-proto==1.34.0
      - opentelemetry-sdk==1.34.0
      - opentelemetry-semantic-conventions==0.55b0
      - opentelemetry-util-http==0.55b0
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - orjson==3.9.10
      - oss2==2.17.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.1.3
      - peft==0.4.0
      - pillow==10.1.0
      - pip==24.2
      - posthog==4.2.0
      - preshed==3.0.9
      - protobuf==3.20.0
      - psutil==5.9.6
      - py-cpuinfo==9.0.0
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.8
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pydantic==1.10.13
      - pydub==0.25.1
      - pyparsing==3.1.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dotenv==1.0.0
      - python-multipart==0.0.6
      - pytorch-crf==0.7.2
      - pytorch-lightning==1.9.5
      - pytz==2023.3.post1
      - referencing==0.31.0
      - regex==2023.10.3
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rouge==1.0.1
      - rpds-py==0.12.0
      - rsa==4.9
      - safetensors==0.4.0
      - scikit-image==0.25.1
      - scikit-learn==1.2.2
      - scipy==1.11.3
      - seaborn==0.13.2
      - segment-anything==1.0
      - semantic-version==2.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.35.0
      - setproctitle==1.3.3
      - setuptools==60.2.0
      - shortuuid==1.0.11
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - starlette==0.27.0
      - supervision==0.25.1
      - svgwrite==1.4.3
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - thinc==8.2.2
      - threadpoolctl==3.2.0
      - tifffile==2025.1.10
      - tiktoken==0.7.0
      - timm==0.6.13
      - tokenizers==0.13.3
      - tomli==2.2.1
      - toolz==0.12.0
      - torch==2.0.1
      - torchmetrics==1.2.1
      - torchvision==0.15.2
      - tqdm==4.65.2
      - transformers==4.31.0
      - triton==2.0.0
      - typeguard==4.4.2
      - typer==0.9.0
      - typing-extensions==4.13.0
      - tzdata==2023.3
      - uc-micro-py==1.0.2
      - urllib3==1.26.20
      - uvicorn==0.24.0.post1
      - uvloop==0.21.0
      - wandb==0.16.0
      - wasabi==1.1.2
      - watchfiles==1.0.5
      - wavedrom==2.0.3.post3
      - weasel==0.3.4
      - websocket-client==1.8.0
      - websockets==12.0
      - werkzeug==3.0.1
      - wikipedia==1.4.0
      - wrapt==1.17.2
      - xxhash==3.4.1
      - yapf==0.40.1
      - yarl==1.9.2
      - zipp==3.21.0
prefix: /shared/nas/data/m1/jk100/.conda/envs/partonomy
