name: /scratch/blume5/envs/segllm2
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-12.1.1
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.40=ha1999f0_7
  - binutils_linux-64=2.40=hb3c18ed_4
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cuda-cccl=12.1.109=0
  - cuda-command-line-tools=12.1.1=0
  - cuda-compiler=12.1.1=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cudart-static=12.1.105=0
  - cuda-cuobjdump=12.1.111=0
  - cuda-cupti=12.1.105=0
  - cuda-cupti-static=12.1.105=0
  - cuda-cuxxfilt=12.1.105=0
  - cuda-documentation=12.1.105=0
  - cuda-driver-dev=12.1.105=0
  - cuda-gdb=12.1.105=0
  - cuda-libraries=12.1.1=0
  - cuda-libraries-dev=12.1.1=0
  - cuda-libraries-static=12.1.1=0
  - cuda-nsight=12.1.105=0
  - cuda-nsight-compute=12.1.1=0
  - cuda-nvcc=12.1.105=0
  - cuda-nvdisasm=12.1.105=0
  - cuda-nvml-dev=12.1.105=0
  - cuda-nvprof=12.1.105=0
  - cuda-nvprune=12.1.105=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvrtc-static=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-nvvp=12.1.105=0
  - cuda-opencl=12.1.105=0
  - cuda-opencl-dev=12.1.105=0
  - cuda-profiler-api=12.1.105=0
  - cuda-runtime=12.1.1=0
  - cuda-sanitizer-api=12.1.105=0
  - cuda-toolkit=12.1.1=0
  - cuda-tools=12.1.1=0
  - cuda-visual-tools=12.1.1=0
  - expat=2.7.1=h6a678d5_0
  - gcc_impl_linux-64=11.4.0=h00c12a0_13
  - gcc_linux-64=11.4.0=ha077dfb_4
  - gds-tools=1.6.1.9=0
  - geos=3.14.0=h480dda7_0
  - gxx_impl_linux-64=11.4.0=h634f3ee_13
  - gxx_linux-64=11.4.0=h35bfe5d_4
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libcublas=12.1.3.1=0
  - libcublas-dev=12.1.3.1=0
  - libcublas-static=12.1.3.1=0
  - libcufft=11.0.2.54=0
  - libcufft-dev=11.0.2.54=0
  - libcufft-static=11.0.2.54=0
  - libcufile=1.6.1.9=0
  - libcufile-dev=1.6.1.9=0
  - libcufile-static=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcurand-dev=10.3.2.106=0
  - libcurand-static=10.3.2.106=0
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.4.5.107=0
  - libcusolver-dev=11.4.5.107=0
  - libcusolver-static=11.4.5.107=0
  - libcusparse=12.1.0.106=0
  - libcusparse-dev=12.1.0.106=0
  - libcusparse-static=12.1.0.106=0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_6
  - libgcc-devel_linux-64=11.4.0=h8f596e0_113
  - libgcc-ng=15.2.0=h69a702a_6
  - libgomp=15.2.0=h767d61c_6
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=12.1.0.40=0
  - libnpp-dev=12.1.0.40=0
  - libnpp-static=12.1.0.40=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.2.0.2=0
  - libnvjpeg-dev=12.2.0.2=0
  - libnvjpeg-static=12.2.0.2=0
  - libnvvm-samples=12.1.105=0
  - libsanitizer=11.4.0=h5763a12_13
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_6
  - libstdcxx-devel_linux-64=11.4.0=h8f596e0_113
  - libstdcxx-ng=15.2.0=h4852527_6
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2023.1.1.4=0
  - nvitop=1.5.3=pyh707e725_0
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - readline=8.3=hc2a1206_0
  - rhash=1.4.6=hb9d3cd8_1
  - ripgrep=14.1.1=h8fae777_1
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.1.0
      - accelerate==0.31.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.3.4
      - aiohttp==3.10.1
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autobahn==23.6.2
      - automat==22.10.0
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.1
      - black==21.4b2
      - certifi==2025.10.5
      - cffi==1.16.0
      - charset-normalizer==3.4.4
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==4.1.0
      - comm==0.2.2
      - constantly==23.10.4
      - contourpy==1.3.0
      - cryptography==43.0.0
      - cycler==0.12.1
      - cython==3.0.10
      - datasets==2.20.0
      - debugpy==1.8.2
      - decorator==5.1.1
      - deepspeed==0.14.4
      - detectron2==0.6
      - diffusers==0.35.1
      - dill==0.3.8
      - distro==1.9.0
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.8.0
      - einops-exts==0.0.4
      - email-validator==2.2.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fairscale==0.4.13
      - fastapi==0.111.1
      - fastapi-cli==0.0.4
      - ffmpy==0.3.2
      - filelock==3.20.0
      - flash-attn==2.5.9.post1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2025.9.0
      - ftfy==6.2.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google==3.0.0
      - gradio==4.38.1
      - gradio-client==1.1.0
      - grpcio==1.65.4
      - h11==0.14.0
      - hf-xet==1.1.10
      - hjson==3.1.0
      - hkdf==0.0.3
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.35.3
      - humanize==4.10.0
      - hydra-core==1.3.2
      - hyperlink==21.0.0
      - idna==3.11
      - imageio==2.36.0
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - incremental==24.7.2
      - iopath==0.1.9
      - ipykernel==6.29.5
      - ipython==8.26.0
      - iterable-io==1.0.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.11.1
      - joblib==1.5.2
      - jpeg4py==0.1.4
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - latex2mathml==3.78.1
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - linkify-it-py==2.0.3
      - lit==18.1.8
      - llava==1.1.1
      - lxml==5.2.2
      - magic-wormhole==0.14.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markdown2==2.5.4
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - motmetrics==1.4.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - multiscaledeformableattention==1.0
      - mypy-extensions==1.0.0
      - narwhals==2.7.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.1
      - numpy==2.2.6
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - open-clip-torch==2.0.2
      - openai==2.5.0
      - opencv-python==4.10.0.84
      - orjson==3.10.6
      - packaging==25.0
      - pandas==2.2.2
      - panopticapi==0.1
      - parso==0.8.4
      - pathspec==0.12.1
      - peft==0.11.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - pip-date==1.0.5
      - platformdirs==4.2.2
      - portalocker==2.10.1
      - prompt-toolkit==3.0.47
      - propcache==0.4.1
      - protobuf==4.25.4
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycocotools==2.0.10
      - pycparser==2.22
      - pydantic==2.8.0
      - pydantic-core==2.20.0
      - pydot==3.0.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pynacl==1.5.0
      - pyopenssl==24.2.1
      - pyparsing==3.2.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytorch-lightning==2.1.0
      - pytz==2024.1
      - pyyaml==6.0.3
      - pyzmq==26.0.3
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.5
      - rich==13.7.1
      - rpds-py==0.19.0
      - ruff==0.5.4
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - segment-anything==1.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.7.1
      - service-identity==24.1.0
      - setproctitle==1.3.3
      - shapely==1.7.1
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - spake2==0.8
      - stack-data==0.6.3
      - starlette==0.37.2
      - svgwrite==1.4.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - threadpoolctl==3.6.0
      - tifffile==2024.9.20
      - tikzplotlib==0.10.1
      - timm==1.0.8
      - tokenizers==0.20.1
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.3.1+cu121
      - torchaudio==2.3.1+cu121
      - torchmetrics==1.8.2
      - torchvision==0.18.1+cu121
      - tornado==6.4.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.1
      - triton==2.3.1
      - twisted==24.3.0
      - txaio==23.1.1
      - txtorcon==23.11.0
      - typer==0.12.3
      - typing-extensions==4.15.0
      - tzdata==2024.1
      - uc-micro-py==1.0.3
      - urllib3==2.5.0
      - uvicorn==0.30.3
      - uvloop==0.19.0
      - visdom==0.2.4
      - wandb==0.17.3
      - watchfiles==0.22.0
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.0.3
      - wormhole==0.1.0
      - xmltodict==0.13.0
      - xxhash==3.4.1
      - yacs==0.1.8
      - yarl==1.9.4
      - zipp==3.19.2
      - zipstream-ng==1.7.1
      - zope-interface==6.4.post2
prefix: /scratch/blume5/envs/segllm2
