wandb_version: 1

local_rank:
  desc: null
  value: 0
version:
  desc: null
  value: liuhaotian/llava-llama-2-13b-chat-lightning-preview
vis_save_path:
  desc: null
  value: ./vis_output
precision:
  desc: null
  value: bf16
image_size:
  desc: null
  value: 1024
model_max_length:
  desc: null
  value: 512
lora_r:
  desc: null
  value: 8
vision_tower:
  desc: null
  value: openai/clip-vit-large-patch14
load_in_8bit:
  desc: null
  value: false
load_in_4bit:
  desc: null
  value: false
dataset:
  desc: null
  value: sem_seg||refer_seg||vqa||reason_seg||explanatory_seg
sample_rates:
  desc: null
  value: 9,3,3,1,9
sem_seg_data:
  desc: null
  value: ade20k||cocostuff||pascal_part||paco_lvis||mapillary
refer_seg_data:
  desc: null
  value: refclef||refcoco||refcoco+||refcocog
explanatory_seg_data:
  desc: null
  value: true
wandb:
  desc: null
  value: false
wandb_project_name:
  desc: null
  value: plum-training
vqa_data:
  desc: null
  value: llava_instruct_150k
reason_seg_data:
  desc: null
  value: ReasonSeg|train
val_dataset:
  desc: null
  value: ReasonSeg|val
dataset_dir:
  desc: null
  value: /shared/nas/data/m1/jk100/code/OpenAttrLibrary/LISA/dataset
log_base_dir:
  desc: null
  value: ./runs
exp_name:
  desc: null
  value: plum-13b_kld_0_dice_0_v1_partonomy
epochs:
  desc: null
  value: 50
steps_per_epoch:
  desc: null
  value: 500
batch_size:
  desc: null
  value: 2
grad_accumulation_steps:
  desc: null
  value: 10
val_batch_size:
  desc: null
  value: 1
workers:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.0003
ce_loss_weight:
  desc: null
  value: 1.0
dice_loss_weight:
  desc: null
  value: 0.0
dice_scale_factor:
  desc: null
  value: 1000.0
bce_loss_weight:
  desc: null
  value: 2.0
kld_loss_weight:
  desc: null
  value: 0.0
kld_sigma:
  desc: null
  value: 1.0
seg_cls_loss_weight:
  desc: null
  value: 0.0
seg_cls_loss_per_cls_weight:
  desc: null
  value:
  - 0.2
  - 1.0
  - 1.0
use_teacher_ref:
  desc: null
  value: false
use_bidir_bio:
  desc: null
  value: false
use_cross_attn_bio:
  desc: null
  value: false
lora_alpha:
  desc: null
  value: 16
lora_dropout:
  desc: null
  value: 0.05
lora_target_modules:
  desc: null
  value: q_proj,v_proj
explanatory:
  desc: null
  value: 0.1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
num_classes_per_sample:
  desc: null
  value: 5
exclude_val:
  desc: null
  value: false
no_eval:
  desc: null
  value: false
eval_only:
  desc: null
  value: false
vision_pretrained:
  desc: null
  value: /shared/nas/data/m1/jk100/code/OpenAttrLibrary/LISA/weights/sam_vit_h_4b8939.pth
out_dim:
  desc: null
  value: 256
resume:
  desc: null
  value: ''
print_freq:
  desc: null
  value: 1
start_epoch:
  desc: null
  value: 0
gradient_checkpointing:
  desc: null
  value: true
train_mask_decoder:
  desc: null
  value: true
use_mm_start_end:
  desc: null
  value: true
auto_resume:
  desc: null
  value: true
conv_type:
  desc: null
  value: llava_v1
log_dir:
  desc: null
  value: ./runs/plum-13b_kld_0_dice_0_v1_partonomy
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1743323579.258735
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.31.0
      8:
      - 5
      13: linux-x86_64
